# Generated by Django 4.1.4 on 2023-01-05 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_api', '0002_mail_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(help_text='7XXXXXXXXXX', max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='schedule',
            field=models.CharField(blank=True, help_text='* * * * * (Minute, Hour, Day_of_Month, Month, Day_of_Week', max_length=30, null=True, verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='start_at',
            field=models.DateTimeField(verbose_name='Старт'),
        ),
    ]
