# Generated by Django 4.1.4 on 2023-01-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_api', '0003_alter_client_mobile_alter_mail_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator',
            field=models.IntegerField(blank=True, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tag_list',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Список тэгов'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('Future', 'future'), ('Active', 'active'), ('Paused', 'paused'), ('Outdated', 'outdated')], default='Future', max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
