# Generated by Django 4.1.4 on 2023-01-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_api', '0005_remove_message_status_mail_time_gap_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('future', 'future'), ('active', 'active'), ('paused', 'paused'), ('outdated', 'outdated')], default='future', max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail_api.mail', verbose_name='Рассылка'),
        ),
    ]
