# Generated by Django 4.1.4 on 2023-01-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_api', '0006_alter_mail_status_alter_message_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(blank=True, choices=[('future', 'future'), ('active', 'active'), ('paused', 'paused'), ('outdated', 'outdated')], default='future', max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
