# Generated by Django 4.1.4 on 2023-01-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_api', '0007_alter_mail_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='mail',
            name='clients',
            field=models.ManyToManyField(blank=True, to='mail_api.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Тэг'),
        ),
    ]
